name: Postman API Test Automation

on:
  push:
    branches: [ main ]

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Newman
        run: |
          npm install -g newman
      - name: Run Postman collection (local)
        # If your collection is in the main repository:
        run: |
          newman run weather.json
      # OR
      - name: Download Postman collection (from separate repository)
        uses: actions/download-artifact@v3
        with:
          name: postman_collection
          path: collections
      - name: Run Postman collection (downloaded)
        # If your collection is in a separate repository:
        run: |
          newman run weather.json
